from API.user import *
from API.songs import *
from API.tags import *
from API.albums import *
from API.search import *
from API.stream import *
from API.flag import *
from API.playlist import *
from API.notification import *